import type { PublicApiRouteCatalogItem } from "@marine/shared";

export const PUBLIC_API_ROUTE_CATALOG: PublicApiRouteCatalogItem[] = [
  {
    route: "/api/v1/risk/score",
    method: "GET",
    requiredAuth: "apiKey",
    request: "Query: stationId required, window optional",
    response: "Risk score, confidence, operator summary, recommendation, rate-limit headers",
    summary: "Scores recent station risk from stored observation history.",
  },
  {
    route: "/api/v1/risk/evaluate",
    method: "POST",
    requiredAuth: "apiKey",
    request: "Body: stationId, observedAt, metrics, optional history",
    response: "Evaluated risk, baseline stats, confidence, recommendation, rate-limit headers",
    summary: "Evaluates a caller-supplied observation against deterministic marine rules and baseline history.",
  },
  {
    route: "/api/v1/anomalies",
    method: "GET",
    requiredAuth: "apiKey",
    request: "Query: stationId optional, since optional, limit optional",
    response: "Anomaly list with provenance, applied filters, pagination, rate-limit headers",
    summary: "Returns recent derived anomalies and supporting provenance.",
  },
  {
    route: "/api/v1/alerts",
    method: "GET",
    requiredAuth: "apiKey",
    request: "Query: stationId optional, severity optional, status optional, limit optional",
    response: "Alert list, applied filters, pagination, rate-limit headers",
    summary: "Returns workflow alerts suitable for external operational consumers.",
  },
  {
    route: "/api/v1/validation/summary",
    method: "GET",
    requiredAuth: "apiKey",
    request: "Query: stationId optional, since optional",
    response: "Calibration summary, failure modes, reliability metrics, rate-limit headers",
    summary: "Returns aggregate validation and calibration metrics for issued predictions.",
  },
  {
    route: "/api/v1/validation/outcomes",
    method: "POST",
    requiredAuth: "apiKey",
    request: "Body: evaluationId, observedAt, actualRiskLevel, classification, summary, source",
    response: "Updated evaluation record, rate-limit headers",
    summary: "Attaches an actual outcome to a previously issued prediction.",
  },
  {
    route: "/api/v1/validation/feedback",
    method: "POST",
    requiredAuth: "apiKey",
    request: "Body: evaluationId, useful, optional note",
    response: "Updated evaluation record, rate-limit headers",
    summary: "Attaches operator usefulness feedback to a previously issued prediction.",
  },
  {
    route: "/api/v1/usage/summary",
    method: "GET",
    requiredAuth: "apiKey",
    request: "Query: since optional, limit optional",
    response: "Usage counts, recent requests, route totals, current tier, current rate-limit status",
    summary: "Returns customer-facing usage and current limit posture for the authenticated API key.",
  },
  {
    route: "/api/v1/catalog",
    method: "GET",
    requiredAuth: "apiKey",
    request: "No body",
    response: "Machine-readable public route catalog",
    summary: "Returns a static contract summary for public pilot integrations.",
  },
  {
    route: "/api/admin/keys",
    method: "POST",
    requiredAuth: "adminSession",
    request: "Body: name, tier",
    response: "One-time raw API key plus metadata",
    summary: "Creates a public API key for pilot customer use.",
  },
];
