export type DatabaseColumnType = "text" | "integer" | "real" | "boolean" | "json" | "timestamp";

export interface DatabaseColumnReference {
  table: string;
  column: string;
}

export interface DatabaseColumnSchema {
  name: string;
  type: DatabaseColumnType;
  nullable?: boolean;
  primaryKey?: boolean;
  unique?: boolean;
  defaultValue?: string;
  references?: DatabaseColumnReference;
}

export interface DatabaseTableSchema {
  name: string;
  columns: DatabaseColumnSchema[];
}

const timestampColumns = [
  {
    name: "created_at",
    type: "timestamp",
    defaultValue: "CURRENT_TIMESTAMP",
  },
  {
    name: "updated_at",
    type: "timestamp",
    defaultValue: "CURRENT_TIMESTAMP",
  },
] as const satisfies DatabaseColumnSchema[];

export const databaseSchema: DatabaseTableSchema[] = [
  {
    name: "data_sources",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text" },
      { name: "priority", type: "integer", defaultValue: "0" },
      { name: "base_url", type: "text", nullable: true },
      { name: "active", type: "boolean", defaultValue: "1" },
      ...timestampColumns,
    ],
  },
  {
    name: "regions",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text" },
      { name: "status", type: "text" },
      { name: "summary", type: "text" },
      { name: "geometry", type: "json", nullable: true },
      { name: "buoy_count", type: "integer", nullable: true },
      { name: "nearest_buoy_label", type: "text", nullable: true },
      { name: "thermal_anomaly_label", type: "text", nullable: true },
      { name: "current_direction_label", type: "text", nullable: true },
      ...timestampColumns,
    ],
  },
  {
    name: "ingestion_runs",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "source", type: "text" },
      { name: "status", type: "text" },
      { name: "station_count", type: "integer", defaultValue: "0" },
      { name: "inserted_rows", type: "integer", defaultValue: "0" },
      { name: "rejected_rows", type: "integer", defaultValue: "0" },
      { name: "started_at", type: "integer" },
      { name: "finished_at", type: "integer", nullable: true },
      ...timestampColumns,
    ],
  },
  {
    name: "observations",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "station_id", type: "text" },
      { name: "source", type: "text" },
      { name: "observed_at", type: "integer" },
      { name: "sea_surface_temp_c", type: "real", nullable: true },
      { name: "wave_height_m", type: "real", nullable: true },
      { name: "wind_speed_mps", type: "real", nullable: true },
      { name: "pressure_hpa", type: "real", nullable: true },
      { name: "ingestion_run_id", type: "text", references: { table: "ingestion_runs", column: "id" } },
      { name: "source_timestamp", type: "text" },
      { name: "source_reference", type: "text" },
      { name: "raw_line", type: "text" },
      { name: "created_at", type: "integer" },
    ],
  },
  {
    name: "provenance_records",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "ingestion_run_id", type: "text", references: { table: "ingestion_runs", column: "id" } },
      { name: "source", type: "text" },
      { name: "source_station_id", type: "text" },
      { name: "source_timestamp", type: "text" },
      { name: "source_reference", type: "text" },
      { name: "record_type", type: "text" },
      { name: "record_id", type: "text" },
      { name: "payload_json", type: "json" },
      { name: "created_at", type: "integer" },
    ],
  },
  {
    name: "station_metrics",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "station_id", type: "text", nullable: true, references: { table: "stations", column: "id" } },
      { name: "region_key", type: "text" },
      { name: "metric_type", type: "text" },
      { name: "metric_value", type: "real", nullable: true },
      { name: "metric_unit", type: "text", nullable: true },
      { name: "source", type: "text" },
      { name: "observed_at", type: "integer" },
      { name: "ingestion_run_id", type: "text", references: { table: "ingestion_runs", column: "id" } },
      { name: "source_timestamp", type: "text" },
      { name: "source_reference", type: "text" },
      { name: "created_at", type: "integer" },
    ],
  },
  {
    name: "derived_signals",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "station_id", type: "text", nullable: true, references: { table: "stations", column: "id" } },
      { name: "region_key", type: "text" },
      { name: "signal_type", type: "text" },
      { name: "signal_value", type: "real", nullable: true },
      { name: "signal_label", type: "text", nullable: true },
      { name: "severity", type: "text", nullable: true },
      { name: "source", type: "text" },
      { name: "observed_at", type: "integer" },
      { name: "ingestion_run_id", type: "text", references: { table: "ingestion_runs", column: "id" } },
      { name: "source_timestamp", type: "text" },
      { name: "source_reference", type: "text" },
      { name: "created_at", type: "integer" },
    ],
  },
  {
    name: "live_ingestion_worker_runs",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "status", type: "text" },
      { name: "started_at", type: "integer" },
      { name: "completed_at", type: "integer" },
      { name: "duration_ms", type: "integer" },
      { name: "inserted_count", type: "integer", defaultValue: "0" },
      { name: "rejected_count", type: "integer", defaultValue: "0" },
      { name: "rejection_reasons_json", type: "json" },
      { name: "created_at", type: "integer" },
    ],
  },
  {
    name: "live_ingestion_reports",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "worker_run_id", type: "text", references: { table: "live_ingestion_worker_runs", column: "id" } },
      { name: "source", type: "text" },
      { name: "started_at", type: "integer" },
      { name: "completed_at", type: "integer" },
      { name: "duration_ms", type: "integer" },
      { name: "inserted_count", type: "integer", defaultValue: "0" },
      { name: "rejected_count", type: "integer", defaultValue: "0" },
      { name: "rejection_reasons_json", type: "json" },
      { name: "status", type: "text" },
      { name: "run_id", type: "text", nullable: true },
      { name: "error", type: "text", nullable: true },
      { name: "created_at", type: "integer" },
    ],
  },
  {
    name: "operational_alerts",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "source", type: "text" },
      { name: "rule_type", type: "text" },
      { name: "severity", type: "text" },
      { name: "status", type: "text" },
      { name: "title", type: "text" },
      { name: "detail", type: "text", nullable: true },
      { name: "metadata_json", type: "json", nullable: true },
      { name: "detected_at", type: "integer" },
      { name: "resolved_at", type: "integer", nullable: true },
      ...timestampColumns,
    ],
  },
  {
    name: "datasets",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text" },
      { name: "category", type: "text" },
      { name: "region_id", type: "text", references: { table: "regions", column: "id" } },
      { name: "status", type: "text" },
      { name: "record_count", type: "integer", nullable: true },
      { name: "refreshed_at", type: "timestamp", nullable: true },
      { name: "metadata", type: "json", nullable: true },
      ...timestampColumns,
    ],
  },
  {
    name: "data_explorer_presets",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text" },
      { name: "scope", type: "text", defaultValue: "'shared'" },
      { name: "owner_id", type: "text", nullable: true },
      { name: "filters_json", type: "json" },
      { name: "created_at", type: "timestamp" },
      { name: "updated_at", type: "timestamp" },
      { name: "last_used_at", type: "timestamp", nullable: true },
      { name: "use_count", type: "integer", defaultValue: "0" },
    ],
  },
  {
    name: "data_explorer_preset_audit_events",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "preset_id", type: "text", nullable: true },
      { name: "preset_name", type: "text" },
      { name: "scope", type: "text" },
      { name: "action", type: "text" },
      { name: "actor_id", type: "text", nullable: true },
      { name: "actor_type", type: "text" },
      { name: "owner_id", type: "text", nullable: true },
      { name: "outcome", type: "text" },
      { name: "reason", type: "text", nullable: true },
      { name: "created_at", type: "timestamp" },
      { name: "metadata_json", type: "json", nullable: true },
    ],
  },
  {
    name: "data_explorer_behavior_events",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "event_type", type: "text" },
      { name: "scope", type: "text" },
      { name: "actor_id", type: "text", nullable: true },
      { name: "actor_label", type: "text", nullable: true },
      { name: "owner_id", type: "text", nullable: true },
      { name: "preset_id", type: "text", nullable: true },
      { name: "preset_name", type: "text", nullable: true },
      { name: "dataset_id", type: "text", nullable: true },
      { name: "dataset_name", type: "text", nullable: true },
      { name: "created_at", type: "timestamp" },
      { name: "source_context_json", type: "json", nullable: true },
    ],
  },
  {
    name: "investigations",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "title", type: "text" },
      { name: "summary", type: "text" },
      { name: "state", type: "text" },
      { name: "region_id", type: "text", nullable: true, references: { table: "regions", column: "id" } },
      { name: "owner", type: "text", nullable: true },
      { name: "confidence", type: "integer", nullable: true },
      ...timestampColumns,
    ],
  },
  {
    name: "investigation_events",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "investigation_id", type: "text", references: { table: "investigations", column: "id" } },
      { name: "event_type", type: "text" },
      { name: "source", type: "text" },
      { name: "actor", type: "text", nullable: true },
      { name: "summary", type: "text" },
      { name: "detail", type: "text", nullable: true },
      { name: "confidence", type: "integer", nullable: true },
      { name: "created_at", type: "integer" },
    ],
  },
  {
    name: "signal_detections",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "signal_type", type: "text" },
      { name: "severity", type: "text" },
      { name: "confidence", type: "integer" },
      { name: "source_type", type: "text" },
      { name: "source_id", type: "text" },
      { name: "region", type: "text" },
      { name: "station_id", type: "text", nullable: true, references: { table: "stations", column: "id" } },
      { name: "title", type: "text" },
      { name: "summary", type: "text" },
      { name: "detail", type: "text" },
      { name: "status", type: "text" },
      { name: "detected_at", type: "integer" },
      { name: "created_at", type: "integer" },
      { name: "updated_at", type: "integer" },
      { name: "linked_investigation_id", type: "text", nullable: true, references: { table: "investigations", column: "id" } },
    ],
  },
  {
    name: "species",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "common_name", type: "text" },
      { name: "scientific_name", type: "text" },
      { name: "conservation_status", type: "text" },
      { name: "habitat_region", type: "text" },
      { name: "summary", type: "text" },
      { name: "created_at", type: "integer" },
      { name: "updated_at", type: "integer" },
    ],
  },
  {
    name: "species_sightings",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "species_id", type: "text", references: { table: "species", column: "id" } },
      { name: "station_id", type: "text", nullable: true },
      { name: "region", type: "text" },
      { name: "observed_at", type: "integer" },
      { name: "latitude", type: "text" },
      { name: "longitude", type: "text" },
      { name: "count", type: "integer" },
      { name: "source", type: "text" },
      { name: "summary", type: "text" },
      { name: "verification_status", type: "text", defaultValue: "'pending'" },
      { name: "verified_at", type: "integer", nullable: true },
      { name: "verified_by", type: "text", nullable: true },
      { name: "created_at", type: "integer" },
    ],
  },
  {
    name: "species_movement_signals",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "species_id", type: "text", references: { table: "species", column: "id" } },
      { name: "signal_id", type: "text", nullable: true, references: { table: "signal_detections", column: "id" } },
      { name: "investigation_id", type: "text", nullable: true, references: { table: "investigations", column: "id" } },
      { name: "movement_type", type: "text" },
      { name: "confidence", type: "integer" },
      { name: "summary", type: "text" },
      { name: "created_at", type: "integer" },
    ],
  },
  {
    name: "ai_analyses",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "investigation_id", type: "text", nullable: true, references: { table: "investigations", column: "id" } },
      { name: "prompt", type: "text" },
      { name: "summary", type: "text", nullable: true },
      { name: "result_payload", type: "json", nullable: true },
      { name: "confidence_label", type: "text", nullable: true },
      ...timestampColumns,
    ],
  },
  {
    name: "alerts",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "title", type: "text" },
      { name: "severity", type: "text" },
      { name: "status", type: "text" },
      { name: "region_id", type: "text", nullable: true, references: { table: "regions", column: "id" } },
      { name: "dataset_id", type: "text", nullable: true, references: { table: "datasets", column: "id" } },
      { name: "investigation_id", type: "text", nullable: true, references: { table: "investigations", column: "id" } },
      { name: "detail", type: "text", nullable: true },
      { name: "detected_at", type: "timestamp", nullable: true },
      ...timestampColumns,
    ],
  },
  {
    name: "reports",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "title", type: "text" },
      { name: "report_type", type: "text" },
      { name: "status", type: "text" },
      { name: "region_id", type: "text", nullable: true, references: { table: "regions", column: "id" } },
      { name: "investigation_id", type: "text", nullable: true, references: { table: "investigations", column: "id" } },
      { name: "author", type: "text", nullable: true },
      { name: "published_at", type: "timestamp", nullable: true },
      { name: "content", type: "text", nullable: true },
      ...timestampColumns,
    ],
  },
  {
    name: "map_layers",
    columns: [
      { name: "label", type: "text", primaryKey: true },
      { name: "description", type: "text" },
      { name: "active", type: "boolean" },
      { name: "accent", type: "text" },
      { name: "sort_order", type: "integer" },
      ...timestampColumns,
    ],
  },
  {
    name: "stations",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text" },
      { name: "slug", type: "text", unique: true },
      { name: "region_id", type: "text", references: { table: "regions", column: "id" } },
      { name: "status", type: "text" },
      { name: "summary", type: "text" },
      { name: "location_label", type: "text" },
      { name: "depth_m", type: "integer", nullable: true },
      { name: "latitude", type: "text", nullable: true },
      { name: "longitude", type: "text", nullable: true },
      { name: "last_reported_at", type: "timestamp", nullable: true },
      { name: "hero_metric", type: "text", nullable: true },
      { name: "sponsor_name", type: "text", nullable: true },
      { name: "operator_name", type: "text", nullable: true },
      { name: "logo_url", type: "text", nullable: true },
      { name: "logo_label", type: "text", nullable: true },
      { name: "exhibit_title", type: "text", nullable: true },
      { name: "accent_color", type: "text", nullable: true },
      { name: "public_description", type: "text", nullable: true },
      ...timestampColumns,
    ],
  },
  {
    name: "station_page_views",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "station_id", type: "text", references: { table: "stations", column: "id" } },
      { name: "view_type", type: "text" },
      { name: "viewed_at", type: "timestamp", nullable: true },
      ...timestampColumns,
    ],
  },
  {
    name: "station_species",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "station_id", type: "text", references: { table: "stations", column: "id" } },
      { name: "name", type: "text" },
      { name: "status", type: "text" },
      { name: "population_trend", type: "text", nullable: true },
      { name: "observed_at", type: "timestamp", nullable: true },
      { name: "notes", type: "text", nullable: true },
      { name: "sort_order", type: "integer", defaultValue: "0" },
      ...timestampColumns,
    ],
  },
  {
    name: "station_sensors",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "station_id", type: "text", references: { table: "stations", column: "id" } },
      { name: "name", type: "text" },
      { name: "category", type: "text" },
      { name: "value", type: "text" },
      { name: "unit", type: "text", nullable: true },
      { name: "status", type: "text" },
      { name: "sampled_at", type: "timestamp", nullable: true },
      { name: "sort_order", type: "integer", defaultValue: "0" },
      ...timestampColumns,
    ],
  },
  {
    name: "station_alerts",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "station_id", type: "text", references: { table: "stations", column: "id" } },
      { name: "title", type: "text" },
      { name: "severity", type: "text" },
      { name: "status", type: "text" },
      { name: "detail", type: "text", nullable: true },
      { name: "detected_at", type: "timestamp", nullable: true },
      { name: "acknowledged_at", type: "timestamp", nullable: true },
      { name: "acknowledged_by", type: "text", nullable: true },
      ...timestampColumns,
    ],
  },
  {
    name: "station_timelines",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "station_id", type: "text", references: { table: "stations", column: "id" } },
      { name: "label", type: "text" },
      { name: "phase", type: "text" },
      { name: "detail", type: "text" },
      { name: "happened_at", type: "timestamp", nullable: true },
      { name: "sort_order", type: "integer", defaultValue: "0" },
      ...timestampColumns,
    ],
  },
  {
    name: "station_content",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "station_id", type: "text", references: { table: "stations", column: "id" } },
      { name: "content_type", type: "text" },
      { name: "title", type: "text" },
      { name: "summary", type: "text" },
      { name: "href", type: "text", nullable: true },
      { name: "published_at", type: "timestamp", nullable: true },
      { name: "sort_order", type: "integer", defaultValue: "0" },
      ...timestampColumns,
    ],
  },
  {
    name: "station_admin_sessions",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "actor_id", type: "text" },
      { name: "actor_role", type: "text" },
      { name: "permissions", type: "json", nullable: true },
      { name: "csrf_token", type: "text" },
      { name: "issued_at", type: "timestamp" },
      { name: "expires_at", type: "timestamp" },
      { name: "last_active_at", type: "timestamp", nullable: true },
      { name: "revoked_at", type: "timestamp", nullable: true },
      { name: "metadata", type: "json", nullable: true },
      ...timestampColumns,
    ],
  },
  {
    name: "station_admin_credentials",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "actor_role", type: "text" },
      { name: "password_hash", type: "text" },
      { name: "salt", type: "text" },
      { name: "mfa_enabled", type: "boolean", defaultValue: "0" },
      { name: "mfa_secret", type: "text", nullable: true },
      { name: "mfa_recovery_codes", type: "json", nullable: true },
      { name: "mfa_enrolled_at", type: "timestamp", nullable: true },
      { name: "mfa_last_verified_at", type: "timestamp", nullable: true },
      ...timestampColumns,
    ],
  },
  {
    name: "station_admin_mfa_challenges",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "actor_id", type: "text" },
      { name: "challenge_purpose", type: "text" },
      { name: "session_id", type: "text", nullable: true, references: { table: "station_admin_sessions", column: "id" } },
      { name: "expires_at", type: "timestamp" },
      { name: "attempts_remaining", type: "integer", defaultValue: "5" },
      { name: "consumed_at", type: "timestamp", nullable: true },
      { name: "metadata", type: "json", nullable: true },
      { name: "created_at", type: "timestamp", defaultValue: "CURRENT_TIMESTAMP" },
    ],
  },
  {
    name: "station_admin_auth_events",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "event_type", type: "text" },
      { name: "actor_id", type: "text", nullable: true },
      { name: "session_id", type: "text", nullable: true },
      { name: "occurred_at", type: "timestamp" },
      { name: "metadata", type: "json", nullable: true },
      { name: "created_at", type: "timestamp", defaultValue: "CURRENT_TIMESTAMP" },
    ],
  },
  {
    name: "station_events",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "station_id", type: "text", references: { table: "stations", column: "id" } },
      { name: "event_type", type: "text" },
      { name: "severity", type: "text" },
      { name: "status", type: "text" },
      { name: "title", type: "text" },
      { name: "summary", type: "text" },
      { name: "detected_at", type: "timestamp" },
      { name: "resolved_at", type: "timestamp", nullable: true },
      { name: "investigation_id", type: "text", nullable: true },
      ...timestampColumns,
    ],
  },
  {
    name: "station_event_evidence",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "event_id", type: "text", references: { table: "station_events", column: "id" } },
      { name: "source", type: "text" },
      { name: "kind", type: "text" },
      { name: "captured_at", type: "timestamp" },
      { name: "detail", type: "text" },
      ...timestampColumns,
    ],
  },
  {
    name: "station_event_notes",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "event_id", type: "text", references: { table: "station_events", column: "id" } },
      { name: "author_id", type: "text" },
      { name: "body", type: "text" },
      ...timestampColumns,
    ],
  },
  {
    name: "station_event_actions",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "event_id", type: "text", references: { table: "station_events", column: "id" } },
      { name: "label", type: "text" },
      { name: "actor_id", type: "text" },
      { name: "performed_at", type: "timestamp" },
      { name: "detail", type: "text", nullable: true },
      ...timestampColumns,
    ],
  },
  {
    name: "station_event_history",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "event_id", type: "text", references: { table: "station_events", column: "id" } },
      { name: "from_status", type: "text", nullable: true },
      { name: "to_status", type: "text" },
      { name: "changed_by", type: "text" },
      { name: "changed_at", type: "timestamp" },
      { name: "reason", type: "text", nullable: true },
      ...timestampColumns,
    ],
  },
  {
    name: "station_investigations",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "station_id", type: "text", references: { table: "stations", column: "id" } },
      { name: "title", type: "text" },
      { name: "description", type: "text", nullable: true },
      { name: "status", type: "text" },
      { name: "owner", type: "text", nullable: true },
      { name: "opened_at", type: "timestamp" },
      { name: "closed_at", type: "timestamp", nullable: true },
      ...timestampColumns,
    ],
  },
  {
    name: "station_admin_audits",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "station_id", type: "text", references: { table: "stations", column: "id" } },
      { name: "actor_id", type: "text" },
      { name: "actor_role", type: "text" },
      { name: "area", type: "text" },
      { name: "changed_fields", type: "json" },
      { name: "changed_at", type: "timestamp" },
      ...timestampColumns,
    ],
  },
];

export const databaseTables = Object.fromEntries(
  databaseSchema.map((table) => [table.name, table]),
) as Record<DatabaseTableSchema["name"], DatabaseTableSchema>;
