import {
  aiLabWorkspaceData,
  dataExplorerRelatedRecords,
  dataExplorerWorkspaceData,
  investigationsTimelineFallbackData,
  investigationsWorkspaceData,
  signalDetectionsFallbackData,
  speciesFallbackData,
  speciesMovementSignalsFallbackData,
  speciesSightingsFallbackData,
  oceanStationAnalytics,
  oceanStationDetails,
  oceanStationsData,
  oceanMapWorkspaceData,
  liveMarineConditionsData,
  reefStressWatchData,
} from "../../web/lib/api/mock-data";

export const apiMockData = {
  aiLabWorkspaceData,
  dataExplorerWorkspaceData,
  dataExplorerRelatedRecords,
  investigationsWorkspaceData,
  investigationsTimelineFallbackData,
  signalDetectionsFallbackData,
  speciesFallbackData,
  speciesSightingsFallbackData,
  speciesMovementSignalsFallbackData,
  oceanMapWorkspaceData,
  liveMarineConditionsData,
  reefStressWatchData,
  oceanStationsData,
  oceanStationDetails,
  oceanStationAnalytics,
};
