import type {
  AiLabWorkspaceData,
  SpeciesMovementSignal,
  SpeciesProfile,
  SpeciesSighting,
  SignalDetection,
  DashboardOverviewData,
  DataExplorerRelatedRecord,
  DataExplorerWorkspaceData,
  InvestigationTimelineItem,
  OceanStationAnalytics,
  InvestigationsWorkspaceData,
  OceanStationDetail,
  OceanStationSummary,
  OceanMapWorkspaceData,
  LiveMarineCondition,
  ReefStressWatchItem,
} from "@/lib/api/types";

export const MOCK_METADATA = {
  source: "Mock Ocean Systems Feed",
  method: "simulated_model",
  observedAt: "2026-03-13T10:00:00.000Z",
  ingestedAt: "2026-03-13T10:05:00.000Z",
  updatedAt: "2026-03-13T10:05:00.000Z",
  confidenceScore: 85,
  coverageScore: 90,
  verificationState: "modeled" as const,
};

export const dashboardOverviewData: DashboardOverviewData = {
  metrics: [
    { label: "Species Tracked", value: "2,847", change: 12, icon: "fish", color: "cyan" },
    { label: "Sea Surface Temp", value: "18.4", unit: "°C", change: 2.1, icon: "thermometer", color: "amber" },
    { label: "Current Speed", value: "3.2", unit: "kn", change: -0.4, icon: "wind", color: "violet" },
    { label: "Ocean Coverage", value: "94.7", unit: "%", change: 0.3, icon: "droplets", color: "emerald" },
    { label: "Active Sensors", value: "1,204", change: -5, icon: "activity", color: "rose" },
    { label: "Anomalies Detected", value: "7", change: 2, icon: "alert-circle", color: "rose" },
  ],
  missions: [
    { id: "MSN-041", name: "Pacific Coral Survey", location: "Great Barrier Reef", status: "In Progress", progress: 68, eta: "3 days" },
    { id: "MSN-039", name: "Deep-Sea Vent Mapping", location: "Mid-Atlantic Ridge", status: "In Progress", progress: 31, eta: "12 days" },
    { id: "MSN-044", name: "Whale Migration Track", location: "North Pacific Ocean", status: "Pending", progress: 5, eta: "18 days" },
    { id: "MSN-038", name: "Kelp Forest Assessment", location: "California Coast", status: "Complete", progress: 100, eta: "Done" },
  ],
  activity: [
    { type: "sensor", text: "Buoy ATLAS-19 transmitted depth profile (0–800 m)", time: "1 min ago" },
    { type: "alert", text: "Temperature anomaly flagged: sector 14-C, +2.4 °C", time: "4 min ago" },
    { type: "species", text: "New sighting logged: Balaenoptera musculus (ID BW-0042)", time: "11 min ago" },
    { type: "report", text: "Field report submitted: MSN-041 Phase 2 complete", time: "43 min ago" },
    { type: "sensor", text: "Glider GLD-07 surfaced and synced — 4,320 new data points", time: "1 hr ago" },
    { type: "alert", text: "Oxygen depletion warning in monitoring zone Z-08", time: "2 hr ago" },
  ],
  quickAccess: [
    { label: "Dashboard", desc: "Live marine overview and anomaly summary", href: "/", color: "cyan" },
    { label: "Investigations", desc: "Track active anomaly cases", href: "/investigations", color: "emerald" },
    { label: "Station 46042 Risk", desc: "Open the current station risk assessment", href: "/v1/risk/46042", color: "amber" },
    { label: "Station 41009 Risk", desc: "Open the current station risk assessment", href: "/v1/risk/41009", color: "violet" },
  ],
  anomalySummary: {
    totalAnomalies: 7,
    elevatedAnomalies: 2,
    criticalAnomalies: 1,
    regionsAffected: 3,
    trendDirection: "up",
  },
};

export const liveMarineConditionsData: LiveMarineCondition[] = [
  {
    stationId: "46042",
    timestamp: "2026-03-18T10:50:00.000Z",
    sstC: 17.1,
    waveHeightM: 1.24,
    windSpeedMps: 7.0,
    pressureHpa: 1015.6,
  },
  {
    stationId: "41009",
    timestamp: "2026-03-18T10:40:00.000Z",
    sstC: 23.3,
    waveHeightM: 1.7,
    windSpeedMps: 5.2,
    pressureHpa: 1013.2,
  },
];

export const reefStressWatchData: ReefStressWatchItem[] = [
  {
    region: "Great Barrier Reef",
    stationId: null,
    timestamp: "2026-03-18T10:00:00.000Z",
    sstAnomalyC: 1.8,
    hotSpotC: 1.4,
    dhw: 6.2,
    stressLevel: "alert_level_1",
    source: "noaa_coral_reef_watch",
    outputClass: "derived",
  },
  {
    region: "Caribbean",
    stationId: null,
    timestamp: "2026-03-18T10:00:00.000Z",
    sstAnomalyC: 0.9,
    hotSpotC: 0.6,
    dhw: 3.1,
    stressLevel: "watch",
    source: "noaa_coral_reef_watch",
    outputClass: "derived",
  },
];

export const investigationsWorkspaceData: InvestigationsWorkspaceData = {
  filterGroups: [
    { label: "Investigation Type", value: "Thermal anomaly", accent: "cyan" },
    { label: "Region", value: "North Pacific / Sector 14-C", accent: "amber" },
    { label: "Time Window", value: "Last 72 hours", accent: "emerald" },
    { label: "Species Impact", value: "Coral reef communities", accent: "cyan" },
  ],
  signalMetrics: [
    { label: "Signals linked", value: "18", delta: "+4", icon: "radar" },
    { label: "Data sources", value: "7", delta: "+1", icon: "layers" },
    { label: "Priority score", value: "82", delta: "+9", icon: "shield-alert" },
  ],
  analysisTracks: [
    {
      id: "TRK-201",
      title: "Surface temperature acceleration",
      summary: "Elevated SST continues to widen eastward beyond the historic seasonal envelope.",
      confidence: 86,
      state: "Escalated",
    },
    {
      id: "TRK-187",
      title: "Chlorophyll suppression overlap",
      summary: "Bloom density is tapering inside the same grid cells as the thermal front.",
      confidence: 72,
      state: "Correlated",
    },
    {
      id: "TRK-193",
      title: "Current shear migration",
      summary: "Current vectors show a moderate shear shift that may explain signal drift near the reef edge.",
      confidence: 61,
      state: "Watch",
    },
  ],
  hypothesisLog: [
    {
      id: "H-04",
      title: "Localized SST surge is the primary bleaching driver",
      owner: "Dr. Clarke",
      updated: "12 min ago",
      status: "Supported",
      notes: "Backed by satellite and buoy agreement across three adjacent grid cells.",
    },
    {
      id: "H-07",
      title: "Current shear is redistributing larvae away from recovery zones",
      owner: "M. Patel",
      updated: "29 min ago",
      status: "Testing",
      notes: "Needs one more drifter pass before the transport model can be promoted.",
    },
    {
      id: "H-09",
      title: "Recent vessel traffic is amplifying acoustic stress markers",
      owner: "A. Romero",
      updated: "1 hr ago",
      status: "Needs Review",
      notes: "Weak evidence so far; likely secondary to thermal and nutrient factors.",
    },
  ],
  evidenceItems: [],
  timeline: [],
  speciesSummary: {
    investigationId: "TRK-201",
    generatedAt: "2026-03-13T11:52:00.000Z",
    speciesCount: 2,
    linkedMovementSignalCount: 2,
    verifiedSightingCount: 1,
    pendingVerificationCount: 1,
    entries: [
      {
        speciesId: "SP-BLUE-WHALE",
        commonName: "Blue Whale",
        scientificName: "Balaenoptera musculus",
        movementSignalCount: 1,
        verifiedSightingCount: 1,
        pendingVerificationCount: 0,
        matchedStationCount: 1,
        lastObservedAt: "2026-03-13T11:04:00.000Z",
        maxMovementConfidence: 84,
        relevanceScore: 75,
        responseTier: "priority",
        reasonTrail: [
          {
            kind: "linked_movement_signal",
            label: "1 linked movement signal",
            detail: "Primary movement pattern: route deviation. Max confidence 84%.",
          },
          {
            kind: "verified_sighting",
            label: "1 verified sighting",
            detail: "Verified field observations align this species with the active investigation context.",
          },
          {
            kind: "station_overlap",
            label: "1 station overlap",
            detail: "Species sightings share stations with signals already linked to this investigation.",
          },
          {
            kind: "recent_observation",
            label: "Recent observation window",
            detail: "Most recent observation at 2026-03-13 11:04 UTC.",
          },
        ],
      },
      {
        speciesId: "SP-GREEN-TURTLE",
        commonName: "Green Sea Turtle",
        scientificName: "Chelonia mydas",
        movementSignalCount: 1,
        verifiedSightingCount: 0,
        pendingVerificationCount: 1,
        matchedStationCount: 0,
        lastObservedAt: "2026-03-13T10:42:00.000Z",
        maxMovementConfidence: 73,
        relevanceScore: 50,
        responseTier: "elevated",
        reasonTrail: [
          {
            kind: "linked_movement_signal",
            label: "1 linked movement signal",
            detail: "Primary movement pattern: habitat exit. Max confidence 73%.",
          },
          {
            kind: "pending_verification",
            label: "1 pending verification",
            detail: "New ecological observations are waiting for review before they are promoted into the evidence trail.",
          },
          {
            kind: "recent_observation",
            label: "Recent observation window",
            detail: "Most recent observation at 2026-03-13 10:42 UTC.",
          },
        ],
      },
    ],
    explainabilityNote:
      "Correlation scores are deterministic and derived from linked movement signals, verification-aware sightings, and station overlap already present in the investigation context.",
  },
};

export const investigationsTimelineFallbackData: InvestigationTimelineItem[] = [
  // Evidence-related fallback timeline events removed as part of ghost UI purge
  {
    id: "TL-004",
    timestamp: "2026-03-17T06:45:00Z",
    eventType: "hypothesis_tested",
    source: "Dr. Clarke",
    summary: "Hypothesis H-04: SST surge as primary driver — supported by evidence",
  },
  {
    id: "TL-005",
    timestamp: "2026-03-17T08:00:00Z",
    eventType: "track_escalated",
    source: "Analysis canvas",
    summary: "Track TRK-201 escalated due to increasing confidence (86%)",
  },
  {
    id: "TL-006",
    timestamp: "2026-03-17T09:30:00Z",
    eventType: "evidence_promoted",
    source: "Reef Team Bravo",
    summary: "Field report visually confirms paling in eastern shelf transects",
  },
];

function buildSignalFallbackData(): SignalDetection[] {
  const now = Date.now();
  const anomalyTotal = dashboardOverviewData.anomalySummary?.totalAnomalies ?? 0;
  const criticalTotal = dashboardOverviewData.anomalySummary?.criticalAnomalies ?? 0;
  const elevatedTotal = dashboardOverviewData.anomalySummary?.elevatedAnomalies ?? 0;

  const oxygenActivity = dashboardOverviewData.activity.find((item) =>
    item.type === "alert" && item.text.toLowerCase().includes("oxygen"),
  );

  const stationHealthSignal: SignalDetection = {
    id: "SIG-STATION-001",
    signalType: "station_health",
    severity: "medium",
    confidence: 69,
    sourceType: "station_network",
    sourceId: "active-sensors",
    region: "North Pacific",
    stationId: null,
    title: "Station health variance detected",
    summary: "Active sensor count dipped compared with baseline for this cycle.",
    detail: "Sensor operations show a minor but persistent decline that should be monitored.",
    status: "monitoring",
    detectedAt: new Date(now - 6 * 60_000).toISOString(),
    createdAt: new Date(now - 6 * 60_000).toISOString(),
    updatedAt: new Date(now - 6 * 60_000).toISOString(),
    linkedInvestigationId: null,
    linkedMissionId: null,
    validationState: "UNVERIFIED",
    validationMetadata: null,
  };

  const thermalSignal: SignalDetection = {
    id: "SIG-THERMAL-001",
    signalType: "thermal_anomaly",
    severity: criticalTotal > 0 ? "critical" : elevatedTotal > 0 ? "high" : "medium",
    confidence: Math.min(95, 62 + anomalyTotal * 4),
    sourceType: "dashboard_anomaly_summary",
    sourceId: "dashboard-anomaly-summary",
    region: "North Pacific",
    stationId: null,
    title: "Thermal anomaly escalation",
    summary: `Detected ${anomalyTotal} active anomalies across monitored regions.`,
    detail: "Anomaly summary indicates persistent heat stress pressure with elevated risk in reef sectors.",
    status: "open",
    detectedAt: new Date(now - 3 * 60_000).toISOString(),
    createdAt: new Date(now - 3 * 60_000).toISOString(),
    updatedAt: new Date(now - 3 * 60_000).toISOString(),
    linkedInvestigationId: null,
    linkedMissionId: null,
    validationState: "CORROBORATED",
    validationMetadata: { automated: true, source_purity: 0.94 },
  };

  const oxygenSignal: SignalDetection = {
    id: "SIG-OXYGEN-001",
    signalType: "oxygen_depletion",
    severity: oxygenActivity ? "high" : "medium",
    confidence: oxygenActivity ? 81 : 64,
    sourceType: "activity_alert_stream",
    sourceId: oxygenActivity ? "activity-oxygen-alert" : "activity-alert-stream",
    region: "Eastern Shelf",
    stationId: null,
    title: "Oxygen depletion risk cluster",
    summary: oxygenActivity?.text ?? "Oxygen metrics indicate a potential depletion trend.",
    detail: "Derived from alert activity stream and associated chemistry trend monitoring.",
    status: "monitoring",
    detectedAt: new Date(now - 9 * 60_000).toISOString(),
    createdAt: new Date(now - 9 * 60_000).toISOString(),
    updatedAt: new Date(now - 9 * 60_000).toISOString(),
    linkedInvestigationId: null,
    linkedMissionId: null,
    validationState: "UNVERIFIED",
    validationMetadata: null,
  };

  return [thermalSignal, oxygenSignal, stationHealthSignal];
}

export const signalDetectionsFallbackData: SignalDetection[] = buildSignalFallbackData();

export const speciesFallbackData: SpeciesProfile[] = [
  {
    id: "SP-BLUE-WHALE",
    commonName: "Blue Whale",
    scientificName: "Balaenoptera musculus",
    conservationStatus: "endangered",
    habitatRegion: "North Pacific",
    summary:
      "Large migratory baleen whale tracked for corridor stability, feeding-ground shifts, and route anomaly detection.",
    ...MOCK_METADATA,
    createdAt: "2026-03-11T08:00:00.000Z",
    updatedAt: "2026-03-13T11:20:00.000Z",
  },
  {
    id: "SP-GREEN-TURTLE",
    commonName: "Green Sea Turtle",
    scientificName: "Chelonia mydas",
    conservationStatus: "endangered",
    habitatRegion: "Eastern Shelf",
    summary:
      "Tag-tracked turtle cohort used to monitor habitat fidelity and oxygen-stress related displacement.",
    ...MOCK_METADATA,
    createdAt: "2026-03-10T07:00:00.000Z",
    updatedAt: "2026-03-13T10:45:00.000Z",
  },
  {
    id: "SP-REEF-SHARK",
    commonName: "Grey Reef Shark",
    scientificName: "Carcharhinus amblyrhynchos",
    conservationStatus: "near_threatened",
    habitatRegion: "Great Barrier Reef",
    summary:
      "Predator indicator species used to detect unusual aggregation and reef-edge movement shifts.",
    ...MOCK_METADATA,
    createdAt: "2026-03-09T12:00:00.000Z",
    updatedAt: "2026-03-13T09:10:00.000Z",
  },
];

export const speciesSightingsFallbackData: SpeciesSighting[] = [
  {
    id: "SIGHT-001",
    ...MOCK_METADATA,
    speciesId: "SP-BLUE-WHALE",
    stationId: "STA-NPC-01",
    region: "North Pacific",
    observedAt: "2026-03-13T11:04:00.000Z",
    latitude: 34.712,
    longitude: -143.118,
    count: 2,
    source: "Acoustic buoy mesh",
    summary: "Two tagged whales exhibited widened spacing along the thermal corridor edge.",
    verificationStatus: "verified",
    verifiedAt: "2026-03-13T11:12:00.000Z",
    verifiedBy: "ops.admin",
    createdAt: "2026-03-13T11:06:00.000Z",
  },
  {
    id: "SIGHT-002",
    ...MOCK_METADATA,
    speciesId: "SP-GREEN-TURTLE",
    stationId: "STA-NPC-01",
    region: "Eastern Shelf",
    observedAt: "2026-03-13T10:42:00.000Z",
    latitude: 33.984,
    longitude: -142.502,
    count: 4,
    source: "ROV visual survey",
    summary: "Tagged turtles shifted downslope relative to the previous monitoring pass.",
    verificationStatus: "pending",
    verifiedAt: null,
    verifiedBy: null,
    createdAt: "2026-03-13T10:44:00.000Z",
  },
  {
    id: "SIGHT-003",
    ...MOCK_METADATA,
    speciesId: "SP-REEF-SHARK",
    stationId: "STA-GBR-02",
    region: "Great Barrier Reef",
    observedAt: "2026-03-13T09:06:00.000Z",
    latitude: -18.421,
    longitude: 147.668,
    count: 7,
    source: "Autonomous drone transect",
    summary: "Higher-than-baseline shark aggregation observed in outer-arc hunting lanes.",
    verificationStatus: "rejected",
    verifiedAt: null,
    verifiedBy: null,
    createdAt: "2026-03-13T09:08:00.000Z",
  },
];

export const speciesMovementSignalsFallbackData: SpeciesMovementSignal[] = [
  {
    id: "MOV-001",
    ...MOCK_METADATA,
    speciesId: "SP-BLUE-WHALE",
    signalId: "SIG-THERMAL-001",
    investigationId: "TRK-201",
    movementType: "route_deviation",
    confidence: 84,
    summary:
      "Blue whale route deviated south of expected corridor while thermal anomaly pressure remained elevated.",
    createdAt: "2026-03-13T11:10:00.000Z",
  },
  {
    id: "MOV-002",
    ...MOCK_METADATA,
    speciesId: "SP-GREEN-TURTLE",
    signalId: "SIG-OXYGEN-001",
    investigationId: "TRK-193",
    movementType: "habitat_exit",
    confidence: 73,
    summary:
      "Green turtle cluster moved away from low oxygen shelf pockets aligned with oxygen depletion signals.",
    createdAt: "2026-03-13T10:48:00.000Z",
  },
  {
    id: "MOV-003",
    ...MOCK_METADATA,
    speciesId: "SP-REEF-SHARK",
    signalId: "SIG-STATION-001",
    investigationId: null,
    movementType: "aggregation_shift",
    confidence: 68,
    summary:
      "Reef shark aggregation intensified near a station health variance zone and remains under watch.",
    createdAt: "2026-03-13T09:14:00.000Z",
  },
];

export const dataExplorerWorkspaceData: DataExplorerWorkspaceData = {
  actions: [
    { label: "Run Query", icon: "play", tone: "primary" },
    { label: "Export CSV", icon: "download", tone: "secondary" },
    { label: "Open Schema", icon: "layers", tone: "secondary" },
  ],
  datasets: [
    {
      id: "DST-104",
      name: "Pacific Thermal Front Observations",
      category: "Temperature",
      region: "North Pacific",
      updated: "8 min ago",
      records: "1.2M",
      status: "Live",
    },
    {
      id: "DST-088",
      name: "Coral Reef Stress Survey Bundle",
      category: "Field Reports",
      region: "Sector 14-C",
      updated: "26 min ago",
      records: "18.4K",
      status: "Curated",
    },
    {
      id: "DST-051",
      name: "Autonomous Buoy Nutrient Profiles",
      category: "Chemistry",
      region: "Eastern Shelf",
      updated: "54 min ago",
      records: "642K",
      status: "Live",
    },
    {
      id: "DST-133",
      name: "Larval Drift Model Ensemble",
      category: "Model Output",
      region: "Reef Boundary",
      updated: "2 hr ago",
      records: "9.8K",
      status: "Draft",
    },
  ],
  previewSeries: [
    { label: "00:00", value: 36 },
    { label: "04:00", value: 52 },
    { label: "08:00", value: 49 },
    { label: "12:00", value: 68 },
    { label: "16:00", value: 74 },
    { label: "20:00", value: 61 },
  ],
  metadata: [
    { label: "Source", value: "NOAA polar composite + buoy fusion" },
    { label: "Coverage", value: "34.2N-35.0N / 142.1W-145.4W" },
    { label: "Cadence", value: "5 minute ingest / daily consolidation" },
    { label: "Schema", value: "temperature_c, depth_m, anomaly_index, grid_id" },
    { label: "Owner", value: "Ocean Systems Lab" },
  ],
  summarySignals: [
    {
      title: "AI summary",
      detail: "The selected dataset clusters strongest around a heat band widening east across the reef edge.",
      tone: "cyan",
    },
    {
      title: "Quality note",
      detail: "Coverage is strong, but low-light imagery rows should be weighted lower in downstream analyses.",
      tone: "amber",
    },
    {
      title: "Suggested join",
      detail: "Pair with dissolved oxygen and chlorophyll feeds to reduce false positives near current shear zones.",
      tone: "emerald",
    },
  ],
};

export const dataExplorerRelatedRecords: Record<string, DataExplorerRelatedRecord[]> = {
  "DST-104": [
    {
      id: "ALT-214",
      title: "Thermal spike detected in reef-edge grid",
      type: "Alert",
      status: "Open",
      updated: "11 min ago",
      summary: "Elevated surface temperature exceeded the seasonal envelope across two adjacent cells.",
    },
    {
      id: "ALT-209",
      title: "Buoy cross-check flagged warming persistence",
      type: "Alert",
      status: "Monitoring",
      updated: "23 min ago",
      summary: "Subsurface confirmation suggests the front is holding deeper than the last modeled pass.",
    },
  ],
  "DST-051": [
    {
      id: "ALT-198",
      title: "Nutrient imbalance cluster",
      type: "Alert",
      status: "Review",
      updated: "47 min ago",
      summary: "Recent chemistry profiles indicate nitrate drift near the eastern shelf transition zone.",
    },
  ],
};

export const oceanMapWorkspaceData: OceanMapWorkspaceData = {
  layers: [
    {
      label: "Sea Surface Temperature",
      description: "Thermal anomaly overlay and hotspot gradients",
      active: true,
      accent: "cyan",
    },
    {
      label: "Current Vectors",
      description: "Directional flow and shear indicators",
      active: true,
      accent: "emerald",
    },
    {
      label: "Buoy Network",
      description: "Live sensor positions and telemetry links",
      active: true,
      accent: "amber",
    },
    {
      label: "Protected Zones",
      description: "Reef boundaries and monitoring sectors",
      active: false,
      accent: "cyan",
    },
    {
      label: "Species Sightings",
      description: "Recent confirmed and pending observation markers",
      active: true,
      accent: "cyan",
      overlayCategory: "sightings",
    },
    {
      label: "Movement Signals",
      description: "Species-linked movement detections at station anchors",
      active: true,
      accent: "amber",
      overlayCategory: "movement_signals",
    },
    {
      label: "Ecological Hotspots",
      description: "Grouped recent species activity zones and hotspot summaries",
      active: true,
      accent: "emerald",
      overlayCategory: "hotspots",
    },
    {
      label: "Corridor Foundations",
      description: "Region groupings prepared for future corridor geometry",
      active: false,
      accent: "cyan",
      overlayCategory: "corridors_foundation",
    },
  ],
  mapStats: [
    { label: "Tracked buoys", value: "32", icon: "satellite" },
    { label: "Active fronts", value: "5", icon: "radar" },
    { label: "Drift routes", value: "11", icon: "route" },
  ],
  regionMetrics: [
    { label: "Region", value: "North Pacific / Sector 14-C" },
    { label: "Thermal anomaly", value: "+2.4 °C above seasonal mean" },
    { label: "Current direction", value: "ENE at 1.9 kn" },
    { label: "Nearest buoy", value: "ATLAS-19 · 18 km east" },
    { label: "Risk status", value: "Elevated reef stress window" },
  ],
  overlayEntities: [
    {
      id: "ALT-214",
      label: "Thermal spike detected in reef-edge grid",
      region: "North Pacific",
      severity: "high",
      status: "Open",
      detail: "Elevated surface temperature exceeded the seasonal envelope across two adjacent cells.",
      detectedAt: "2026-03-13T11:49:00.000Z",
    },
    {
      id: "ALT-209",
      label: "Buoy cross-check flagged warming persistence",
      region: "North Pacific",
      severity: "medium",
      status: "Open",
      detail: "Subsurface confirmation suggests the front is holding deeper than the last modeled pass.",
      detectedAt: "2026-03-13T11:37:00.000Z",
    },
    {
      id: "ALT-198",
      label: "Nutrient imbalance cluster",
      region: "Eastern Shelf",
      severity: "medium",
      status: "Open",
      detail: "Recent chemistry profiles indicate nitrate drift near the eastern shelf transition zone.",
      detectedAt: "2026-03-13T11:06:00.000Z",
    },
  ],
  spatialOverlays: {
    categories: ["sightings", "movement_signals", "hotspots", "corridors_foundation"],
    sightings: [
      {
        id: "SIGHT-001",
        speciesId: "SP-BLUE-WHALE",
        commonName: "Blue Whale",
        region: "North Pacific",
        stationId: "STA-NPC-01",
        latitude: 34.712,
        longitude: -143.118,
        count: 2,
        verificationStatus: "verified",
        observedAt: "2026-03-13T11:04:00.000Z",
        detail: "Two tagged whales observed near the corridor edge.",
      },
      {
        id: "SIGHT-002",
        speciesId: "SP-REEF-MANTA",
        commonName: "Reef Manta",
        region: "Eastern Shelf",
        stationId: null,
        latitude: -18.413,
        longitude: 147.709,
        count: 4,
        verificationStatus: "pending",
        observedAt: "2026-03-13T09:20:00.000Z",
        detail: "Repeated surface feeding observed along the nutrient front.",
      },
    ],
    movementSignals: [
      {
        id: "MOV-001",
        speciesId: "SP-BLUE-WHALE",
        commonName: "Blue Whale",
        region: "North Pacific",
        stationId: "STA-NPC-01",
        latitude: 34.682,
        longitude: -143.141,
        locationSource: "station",
        signalId: "SIG-THERMAL-001",
        investigationId: "TRK-201",
        movementType: "route_deviation",
        confidence: 84,
        createdAt: "2026-03-13T11:10:00.000Z",
        detail: "Route deviation aligned with the thermal anomaly corridor.",
      },
      {
        id: "MOV-002",
        speciesId: "SP-REEF-MANTA",
        commonName: "Reef Manta",
        region: "Eastern Shelf",
        stationId: null,
        latitude: null,
        longitude: null,
        locationSource: "unavailable",
        signalId: "SIG-DRIFT-119",
        investigationId: "TRK-204",
        movementType: "aggregation_shift",
        confidence: 77,
        createdAt: "2026-03-13T10:22:00.000Z",
        detail: "Aggregation shift detected, but only region-level anchor is available.",
      },
    ],
    hotspots: [
      {
        id: "HOTSPOT-STA-NPC-01",
        label: "STA-NPC-01 species activity hotspot",
        region: "North Pacific",
        stationId: "STA-NPC-01",
        latitude: 34.697,
        longitude: -143.13,
        hotspotType: "mixed_activity",
        severity: "high",
        recentSightingCount: 2,
        recentMovementSignalCount: 1,
        observedIndividualCount: 2,
        dominantMovementTypes: ["route_deviation"],
        topSpecies: ["Blue Whale"],
        activityScore: 3,
        detail: "2 recent sightings and 1 movement signal concentrated near the station anchor.",
      },
      {
        id: "HOTSPOT-EASTERN-SHELF",
        label: "Eastern Shelf species activity hotspot",
        region: "Eastern Shelf",
        stationId: null,
        latitude: -18.413,
        longitude: 147.709,
        hotspotType: "mixed_activity",
        severity: "medium",
        recentSightingCount: 1,
        recentMovementSignalCount: 1,
        observedIndividualCount: 4,
        dominantMovementTypes: ["aggregation_shift"],
        topSpecies: ["Reef Manta"],
        activityScore: 2,
        detail: "1 recent sighting and 1 movement signal concentrated in the shelf transition zone.",
      },
    ],
    corridorsFoundation: [
      {
        id: "CORRIDOR-NORTH-PACIFIC",
        label: "North Pacific corridor foundation",
        region: "North Pacific",
        priority: "high",
        hotspotIds: ["HOTSPOT-STA-NPC-01"],
        stationIds: ["STA-NPC-01"],
        movementTypes: ["route_deviation"],
        speciesNames: ["Blue Whale"],
        anchorPoints: [
          {
            label: "STA-NPC-01 species activity hotspot",
            latitude: 34.697,
            longitude: -143.13,
          },
        ],
        geometryStatus: "grouped_without_geometry",
        summary: "North Pacific corridor foundation links 1 hotspot across 1 anchor point; geometry pending.",
      },
    ],
    generatedAt: "2026-03-13T12:00:00.000Z",
    windowDays: 14,
  },
  timelineSteps: [
    { label: "00h", active: false },
    { label: "06h", active: false },
    { label: "12h", active: true },
    { label: "18h", active: false },
    { label: "24h", active: false },
    { label: "36h", active: false },
  ],
};

export const oceanStationsData: OceanStationSummary[] = [
  {
    id: "STA-NPC-01",
    slug: "north-pacific-corridor",
    name: "North Pacific Corridor",
    region: "North Pacific",
    status: "Active Monitoring",
    summary:
      "Flagship station coordinating live reef-edge telemetry where thermal fronts and current shear overlap.",
    locationLabel: "34.6N, 143.2W · Eastern Reef Boundary",
    depthM: 420,
    lastReported: "2 min ago",
    heroMetric: "Coral Stress Index 82",
    branding: {
      sponsorName: "Blue Current Foundation",
      operatorName: "Ocean Systems Lab",
      logoUrl: null,
      logoLabel: "Blue Current x Ocean Systems",
      exhibitTitle: "North Pacific Living Reef Exhibit",
      accentColor: "cyan",
      publicDescription:
        "Explore real-time reef health signals from the North Pacific Corridor and learn how ocean science supports conservation.",
    },
  },
  {
    id: "STA-GBR-02",
    slug: "great-barrier-reef-sector",
    name: "Great Barrier Reef Sector",
    region: "Great Barrier Reef",
    status: "Coral Watch",
    summary:
      "Flagship reef station focused on bleaching thresholds, biodiversity resilience, and visitor education.",
    locationLabel: "18.4S, 147.7E · Outer Reef Arc",
    depthM: 55,
    lastReported: "6 min ago",
    heroMetric: "Bleaching Pressure Index 64",
    branding: {
      sponsorName: "Reef Futures Trust",
      operatorName: "Queensland Marine Observatory",
      logoUrl: null,
      logoLabel: "Reef Futures x Queensland Marine",
      exhibitTitle: "Great Barrier Reef Living Classroom",
      accentColor: "emerald",
      publicDescription:
        "Dive into coral resilience science from one of the most iconic reef ecosystems on Earth.",
    },
  },
  {
    id: "STA-MBY-03",
    slug: "monterey-bay-kelp-forest",
    name: "Monterey Bay Kelp Forest",
    region: "Monterey Bay",
    status: "Canopy Watch",
    summary:
      "Flagship coastal station tracking kelp canopy health, marine mammal corridors, and upwelling dynamics.",
    locationLabel: "36.7N, 122.2W · Monterey Coastal Shelf",
    depthM: 120,
    lastReported: "4 min ago",
    heroMetric: "Kelp Canopy Retention 78%",
    branding: {
      sponsorName: "Pacific Habitat Alliance",
      operatorName: "Monterey Marine Institute",
      logoUrl: null,
      logoLabel: "Pacific Habitat x Monterey Marine",
      exhibitTitle: "Monterey Kelp Forest Discovery Deck",
      accentColor: "amber",
      publicDescription:
        "Follow live kelp forest conditions and learn how upwelling shapes biodiversity along California's coast.",
    },
  },
  {
    id: "STA-MAR-04",
    slug: "mid-atlantic-ridge",
    name: "Mid-Atlantic Ridge",
    region: "Mid-Atlantic Ridge",
    status: "Deep Vent Survey",
    summary:
      "Flagship deep-ocean station monitoring hydrothermal vent plumes, chemosynthetic communities, and tectonic variability.",
    locationLabel: "14.1N, 45.3W · Mid-Atlantic Vent Field",
    depthM: 2450,
    lastReported: "7 min ago",
    heroMetric: "Vent Flux Stability 91",
    branding: {
      sponsorName: "Deep Ocean Discovery Fund",
      operatorName: "Atlantic Ridge Research Consortium",
      logoUrl: null,
      logoLabel: "Deep Ocean Discovery x ARC",
      exhibitTitle: "Mid-Atlantic Ridge Deep-Ocean Theater",
      accentColor: "violet",
      publicDescription:
        "Experience deep-ocean exploration with live hydrothermal vent insights and biodiversity discoveries.",
    },
  },
];

export const oceanStationDetails: Record<string, OceanStationDetail> = {
  "STA-NPC-01": {
    ...oceanStationsData[0],
    species: [
      {
        id: "SPC-001",
        name: "Acropora hyacinthus",
        status: "Stressed",
        populationTrend: "-12% vs seasonal baseline",
        observedAt: "40 min ago",
        notes: "Paling signatures remain concentrated along the northeast transect edge.",
      },
      {
        id: "SPC-002",
        name: "Chromis viridis",
        status: "Monitoring",
        populationTrend: "+4% juvenile density",
        observedAt: "28 min ago",
        notes: "Juvenile schools shifted 1.3 km downslope in the last 24 hours.",
      },
      {
        id: "SPC-003",
        name: "Chelonia mydas",
        status: "Stable",
        populationTrend: "No significant deviation",
        observedAt: "1 hr ago",
        notes: "Tagged migration lane remains intact with minor detours.",
      },
    ],
    sensors: [
      {
        id: "SNS-001",
        name: "Sea Surface Temperature",
        category: "Thermal",
        value: "18.9",
        unit: "C",
        status: "Live",
        sampledAt: "2 min ago",
      },
      {
        id: "SNS-002",
        name: "Current Velocity",
        category: "Hydrodynamics",
        value: "1.9",
        unit: "kn",
        status: "Live",
        sampledAt: "4 min ago",
      },
      {
        id: "SNS-003",
        name: "Dissolved Oxygen",
        category: "Chemistry",
        value: "4.8",
        unit: "mg/L",
        status: "Watch",
        sampledAt: "10 min ago",
      },
    ],
    alerts: [
      {
        id: "STA-ALT-01",
        title: "Thermal anomaly exceeded stress threshold for 37 minutes",
        severity: "high",
        status: "Open",
        detail: "Surface layer remained +2.4 C above climatology while subsurface decay failed overnight.",
        detectedAt: "11 min ago",
        acknowledgedAt: null,
        acknowledgedBy: null,
      },
      {
        id: "STA-ALT-02",
        title: "Dissolved oxygen dipped below advisory floor",
        severity: "medium",
        status: "Monitoring",
        detail: "Two adjacent depth channels reported 4.8 mg/L for three consecutive samples.",
        detectedAt: "20 min ago",
        acknowledgedAt: null,
        acknowledgedBy: null,
      },
    ],
    timeline: [
      {
        id: "STL-001",
        label: "Deployment",
        phase: "Completed",
        detail: "Station array and telemetry uplink commissioned across the corridor.",
        happenedAt: "2026-02-01 09:00 UTC",
      },
      {
        id: "STL-002",
        label: "Thermal Front Expansion",
        phase: "Completed",
        detail: "Heat band expanded east and overlapped protected transects.",
        happenedAt: "2026-03-12 18:30 UTC",
      },
      {
        id: "STL-003",
        label: "Response Window",
        phase: "Active",
        detail: "Field coordination remains active while oxygen validation is prioritized.",
        happenedAt: "2026-03-13 11:00 UTC",
      },
    ],
    content: [
      {
        id: "CNT-001",
        contentType: "brief",
        title: "Morning Reef Stress Brief",
        summary: "Cross-source synthesis of thermal, sensor, and field evidence for mission control.",
        href: "/investigations",
        publishedAt: "30 min ago",
      },
      {
        id: "CNT-002",
        contentType: "assessment",
        title: "North Pacific Station Risk Assessment",
        summary: "Current rule-based station risk view for the active anomaly corridor.",
        href: "/v1/risk/STA-NPC-01",
        publishedAt: "42 min ago",
      },
      {
        id: "CNT-003",
        contentType: "brief",
        title: "Linked Investigation Queue",
        summary: "Open the active anomaly feed tied to this station's current risk signals.",
        href: "/investigations",
        publishedAt: "1 hr ago",
      },
    ],
  },
  "STA-GBR-02": {
    ...oceanStationsData[1],
    species: [
      {
        id: "SPC-101",
        name: "Pocillopora damicornis",
        status: "Monitoring",
        populationTrend: "-4% colony density",
        observedAt: "52 min ago",
        notes: "Patchy paling observed near shallow crest transects.",
      },
      {
        id: "SPC-102",
        name: "Acanthurus triostegus",
        status: "Stable",
        populationTrend: "+2% juvenile presence",
        observedAt: "45 min ago",
        notes: "Schooling behavior remains consistent with seasonal baseline.",
      },
      {
        id: "SPC-103",
        name: "Tridacna gigas",
        status: "Watch",
        populationTrend: "Localized stress in 2 plots",
        observedAt: "58 min ago",
        notes: "Reduced mantle extension in high-irradiance patches.",
      },
    ],
    sensors: [
      {
        id: "SNS-101",
        name: "Sea Surface Temperature",
        category: "Thermal",
        value: "29.1",
        unit: "C",
        status: "Live",
        sampledAt: "6 min ago",
      },
      {
        id: "SNS-102",
        name: "PAR",
        category: "Optical",
        value: "1120",
        unit: "umol/m2/s",
        status: "Live",
        sampledAt: "10 min ago",
      },
      {
        id: "SNS-103",
        name: "Dissolved Oxygen",
        category: "Chemistry",
        value: "5.4",
        unit: "mg/L",
        status: "Live",
        sampledAt: "13 min ago",
      },
    ],
    alerts: [
      {
        id: "STA-ALT-11",
        title: "Midday thermal spike exceeded coral comfort band",
        severity: "medium",
        status: "Monitoring",
        detail: "Two shallow reef grids crossed 29.0 C for 24 minutes.",
        detectedAt: "21 min ago",
        acknowledgedAt: null,
        acknowledgedBy: null,
      },
      {
        id: "STA-ALT-12",
        title: "High irradiance stress window opened",
        severity: "low",
        status: "Open",
        detail: "PAR peaks suggest midday bleaching risk remains elevated.",
        detectedAt: "30 min ago",
        acknowledgedAt: null,
        acknowledgedBy: null,
      },
    ],
    timeline: [
      {
        id: "STL-101",
        label: "Exhibit Launch",
        phase: "Completed",
        detail: "Public reef resilience exhibit launched with live telemetry wall.",
        happenedAt: "2026-02-18 06:30 UTC",
      },
      {
        id: "STL-102",
        label: "Heat Wave Window",
        phase: "Completed",
        detail: "Thermal surge entered the outer arc and triggered rapid response briefings.",
        happenedAt: "2026-03-11 21:15 UTC",
      },
      {
        id: "STL-103",
        label: "Reef Education Week",
        phase: "Active",
        detail: "On-site programming now ties live habitat metrics to visitor learning modules.",
        happenedAt: "2026-03-13 09:00 UTC",
      },
    ],
    content: [
      {
        id: "CNT-101",
        contentType: "brief",
        title: "Coral Heat Watch Brief",
        summary: "Daily operator summary on thermal pressure and expected bleaching stress.",
        href: "/investigations",
        publishedAt: "50 min ago",
      },
      {
        id: "CNT-102",
        contentType: "assessment",
        title: "Great Barrier Reef Station Risk Assessment",
        summary: "Current rule-based station risk view for the outer reef monitoring station.",
        href: "/v1/risk/STA-GBR-02",
        publishedAt: "1 hr ago",
      },
      {
        id: "CNT-103",
        contentType: "brief",
        title: "Linked Investigation Queue",
        summary: "Open the anomaly feed for the current reef stress events and related evidence.",
        href: "/investigations",
        publishedAt: "1 hr ago",
      },
    ],
  },
  "STA-MBY-03": {
    ...oceanStationsData[2],
    species: [
      {
        id: "SPC-201",
        name: "Macrocystis pyrifera",
        status: "Monitoring",
        populationTrend: "-6% canopy cover",
        observedAt: "49 min ago",
        notes: "Canopy thinning persists in two nearshore sectors.",
      },
      {
        id: "SPC-202",
        name: "Enhydra lutris nereis",
        status: "Stable",
        populationTrend: "Foraging lanes unchanged",
        observedAt: "53 min ago",
        notes: "Sea otter rafts remain concentrated in protected kelp beds.",
      },
      {
        id: "SPC-203",
        name: "Sebastes paucispinis",
        status: "Watch",
        populationTrend: "Juvenile density uneven",
        observedAt: "1 hr ago",
        notes: "Patchy recruitment near canopy gaps on west transect.",
      },
    ],
    sensors: [
      {
        id: "SNS-201",
        name: "Nitrate Concentration",
        category: "Chemistry",
        value: "8.2",
        unit: "umol/L",
        status: "Live",
        sampledAt: "4 min ago",
      },
      {
        id: "SNS-202",
        name: "Upwelling Index",
        category: "Hydrodynamics",
        value: "42",
        unit: "index",
        status: "Live",
        sampledAt: "10 min ago",
      },
      {
        id: "SNS-203",
        name: "Kelp Biomass Proxy",
        category: "Optical",
        value: "0.78",
        unit: "ratio",
        status: "Watch",
        sampledAt: "17 min ago",
      },
    ],
    alerts: [
      {
        id: "STA-ALT-21",
        title: "Canopy fragmentation increased in west shelf lane",
        severity: "medium",
        status: "Open",
        detail: "Drone transects show canopy continuity dropped below weekly target.",
        detectedAt: "25 min ago",
        acknowledgedAt: null,
        acknowledgedBy: null,
      },
      {
        id: "STA-ALT-22",
        title: "Nutrient pulse forecast updated",
        severity: "low",
        status: "Monitoring",
        detail: "Expected upwelling pulse may improve canopy recovery in 12-18 hours.",
        detectedAt: "48 min ago",
        acknowledgedAt: null,
        acknowledgedBy: null,
      },
    ],
    timeline: [
      {
        id: "STL-201",
        label: "Kelp Array Upgrade",
        phase: "Completed",
        detail: "New multispectral canopy package integrated with nearshore buoy mesh.",
        happenedAt: "2026-02-22 15:20 UTC",
      },
      {
        id: "STL-202",
        label: "Storm Event Recovery",
        phase: "Completed",
        detail: "Post-storm canopy recovery reached 81% before current downtrend.",
        happenedAt: "2026-03-10 06:10 UTC",
      },
      {
        id: "STL-203",
        label: "Community Science Window",
        phase: "Active",
        detail: "Visitor observations now feed annotated kelp and species storyboards.",
        happenedAt: "2026-03-13 08:45 UTC",
      },
    ],
    content: [
      {
        id: "CNT-201",
        contentType: "brief",
        title: "Kelp Forest Daily Conditions",
        summary: "Operator digest for canopy metrics, nutrient pulses, and biodiversity markers.",
        href: "/investigations",
        publishedAt: "44 min ago",
      },
      {
        id: "CNT-202",
        contentType: "assessment",
        title: "Monterey Bay Station Risk Assessment",
        summary: "Current rule-based station risk view for the kelp forest monitoring station.",
        href: "/v1/risk/STA-MBY-03",
        publishedAt: "59 min ago",
      },
      {
        id: "CNT-203",
        contentType: "brief",
        title: "Linked Investigation Queue",
        summary: "Open the anomaly feed for current kelp canopy and biodiversity signals.",
        href: "/investigations",
        publishedAt: "1 hr ago",
      },
    ],
  },
  "STA-MAR-04": {
    ...oceanStationsData[3],
    species: [
      {
        id: "SPC-301",
        name: "Riftia pachyptila",
        status: "Stable",
        populationTrend: "Colony growth steady",
        observedAt: "55 min ago",
        notes: "Tube worm colony boundaries remained stable across two passes.",
      },
      {
        id: "SPC-302",
        name: "Bathymodiolus azoricus",
        status: "Monitoring",
        populationTrend: "+3% vent-cluster density",
        observedAt: "1 hr ago",
        notes: "Mussel beds expanded slightly near eastern chimney branch.",
      },
      {
        id: "SPC-303",
        name: "Bythograea thermydron",
        status: "Watch",
        populationTrend: "Foraging spread widened",
        observedAt: "1 hr ago",
        notes: "Crab activity increased along cooler plume boundary.",
      },
    ],
    sensors: [
      {
        id: "SNS-301",
        name: "Hydrogen Sulfide",
        category: "Chemistry",
        value: "154",
        unit: "umol/L",
        status: "Live",
        sampledAt: "7 min ago",
      },
      {
        id: "SNS-302",
        name: "Vent Temperature",
        category: "Thermal",
        value: "312",
        unit: "C",
        status: "Live",
        sampledAt: "10 min ago",
      },
      {
        id: "SNS-303",
        name: "Plume Turbidity",
        category: "Optical",
        value: "0.64",
        unit: "ntu",
        status: "Monitoring",
        sampledAt: "17 min ago",
      },
    ],
    alerts: [
      {
        id: "STA-ALT-31",
        title: "Vent chimney B plume spread exceeded baseline envelope",
        severity: "medium",
        status: "Open",
        detail: "Cross-current dispersion increased 14% versus 7-day average.",
        detectedAt: "28 min ago",
        acknowledgedAt: null,
        acknowledgedBy: null,
      },
      {
        id: "STA-ALT-32",
        title: "ROV communication latency event",
        severity: "low",
        status: "Resolved",
        detail: "Transient acoustic relay degradation resolved after channel reset.",
        detectedAt: "1 hr ago",
        acknowledgedAt: null,
        acknowledgedBy: null,
      },
    ],
    timeline: [
      {
        id: "STL-301",
        label: "Deep Vent Commissioning",
        phase: "Completed",
        detail: "Primary vent mooring and plume profiler commissioned on ridge segment.",
        happenedAt: "2026-01-30 04:10 UTC",
      },
      {
        id: "STL-302",
        label: "Chemosynthesis Survey",
        phase: "Completed",
        detail: "Baseline species mosaic established across four chimney clusters.",
        happenedAt: "2026-03-02 13:35 UTC",
      },
      {
        id: "STL-303",
        label: "Public Deep-Ocean Showcase",
        phase: "Active",
        detail: "Live vent telemetry now powers immersive exhibit walkthroughs.",
        happenedAt: "2026-03-13 07:20 UTC",
      },
    ],
    content: [
      {
        id: "CNT-301",
        contentType: "brief",
        title: "Vent Field Operations Brief",
        summary: "Daily synthesis of plume behavior, chemistry, and biology around active chimneys.",
        href: "/investigations",
        publishedAt: "53 min ago",
      },
      {
        id: "CNT-302",
        contentType: "assessment",
        title: "Mid-Atlantic Ridge Station Risk Assessment",
        summary: "Current rule-based station risk view for the vent field monitoring station.",
        href: "/v1/risk/STA-MAR-04",
        publishedAt: "1 hr ago",
      },
      {
        id: "CNT-303",
        contentType: "brief",
        title: "Linked Investigation Queue",
        summary: "Open the anomaly feed for the current vent plume and chemistry events.",
        href: "/investigations",
        publishedAt: "1 hr ago",
      },
    ],
  },
};

export const oceanStationAnalytics: Record<string, OceanStationAnalytics> = {
  "STA-NPC-01": {
    stationId: "STA-NPC-01",
    views: { detail: 2, exhibit: 1, public: 1, total: 4 },
    lastViewedAt: "2026-03-13T11:02:00.000Z",
  },
  "STA-GBR-02": {
    stationId: "STA-GBR-02",
    views: { detail: 1, exhibit: 1, public: 2, total: 4 },
    lastViewedAt: "2026-03-13T11:19:00.000Z",
  },
  "STA-MBY-03": {
    stationId: "STA-MBY-03",
    views: { detail: 2, exhibit: 1, public: 1, total: 4 },
    lastViewedAt: "2026-03-13T11:21:00.000Z",
  },
  "STA-MAR-04": {
    stationId: "STA-MAR-04",
    views: { detail: 1, exhibit: 2, public: 1, total: 4 },
    lastViewedAt: "2026-03-13T11:14:00.000Z",
  },
};

export const aiLabWorkspaceData: AiLabWorkspaceData = {
  promptContext: {
    prompt:
      "Summarize the current reef-edge anomaly using the latest thermal observations, buoy profiles, field reports, and model outputs. Distinguish primary drivers, state confidence, identify uncertainty, and recommend the next best data join.",
    tags: ["Reef stress", "Multi-source", "Investigation support"],
  },
  suggestedPrompts: [
    {
      title: "Compare reef stress drivers",
      detail: "Summarize the strongest signals linking thermal anomalies, chlorophyll changes, and current shear.",
    },
    {
      title: "Draft an evidence brief",
      detail: "Turn the latest anomaly signals into a concise briefing for the field response team.",
    },
    {
      title: "Identify missing context",
      detail: "Highlight which datasets or reports would most reduce uncertainty for the active investigation.",
    },
  ],
  results: [
    {
      title: "Summary",
      body: "The research snapshot suggests heat stress remains the primary explanation for the reef-edge anomaly, with current shear acting as a likely amplifier rather than a competing root cause.",
      icon: "sparkles",
      accent: "cyan",
    },
    {
      title: "Findings",
      body: "Across the active inputs, the strongest agreement appears between buoy depth profiles, satellite temperature composites, and field observations of coral paling along the eastern boundary.",
      icon: "microscope",
      accent: "emerald",
    },
    {
      title: "Evidence",
      body: "High-confidence support comes from the NOAA composite, buoy ATLAS-19 subsurface warming, and the most recent field transect report from Reef Team Bravo.",
      icon: "book-open-text",
      accent: "violet",
    },
    {
      title: "Confidence",
      body: "Overall confidence is moderate-high because three independent source classes converge on the same stress pattern across the same region and time window.",
      icon: "check-circle",
      accent: "emerald",
    },
    {
      title: "Uncertainty",
      body: "Confidence drops when attributing secondary biological impacts, since dissolved oxygen and nighttime recovery data are still sparse in the outer shelf cells.",
      icon: "shield-question",
      accent: "amber",
    },
    {
      title: "Suggested Next Actions",
      body: "Run a dissolved oxygen join, request an additional reef surveillance pass, and generate a briefing note for the investigations workspace to promote the strongest evidence.",
      icon: "target",
      accent: "cyan",
    },
  ],
  sources: [
    {
      id: "SRC-21",
      title: "Pacific Thermal Front Observations",
      type: "Dataset",
      note: "Core thermal anomaly feed aligned with the current research prompt.",
      freshness: "Updated 8 min ago",
    },
    {
      id: "SRC-18",
      title: "Reef Team Bravo Transect 04",
      type: "Field Report",
      note: "Visual confirmation of paling in the eastern shelf transects.",
      freshness: "Submitted 27 min ago",
    },
    {
      id: "SRC-09",
      title: "Coral Stress Ensemble v5",
      type: "Model",
      note: "Forecast layer projecting the next 36-hour stress window.",
      freshness: "Run 1 hr ago",
    },
    {
      id: "SRC-03",
      title: "Shelf Edge Stress Response Review",
      type: "Literature",
      note: "Background context on multi-factor bleaching amplification patterns.",
      freshness: "Indexed this week",
    },
  ],
};
